spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cmlx1218/fosterpet-cmlx-config/    # 配置git仓库的地址
          search-paths: config-repo/test-provider,config-repo/test01-provider     # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: cmlx1218 # git仓库的账号
          password: zq861500116 # git仓库的密码
          basedir: config-repo
        bootstrap: true
#  rabbitmq:
#    host: 39.96.178.201:15672
#    username: guest
#    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: @defaultZone@ #注册中心eurka地址
  instance:
    prefer-ip-address: @addressIP@
    ip-address: ${spring.cloud.client.ip-address}:${server.port}

#endpoints:
#  shutdown:
#    enabled: true #开启优雅关闭方式
management:
  security:
    enabled: false