#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: http://106.14.223.238:90/server/aimymusic-alita-config.git    # 配置git仓库的地址
#          search-paths: config-repo/oauth-center,config-repo/public-provider,config-repo/resource-provider,config-repo/ucenter-provider,config-repo/dance-provider,config-repo/app-provider    # git仓库地址下的相对地址，可以配置多个，用,分割。
#          username: yr9025                                      # git仓库的账号
#          password: xyz123456                                   # git仓库的密码
#          basedir: config-repo


eureka:
  client:
    serviceUrl:
      defaultZone: @defaultZone@ #注册中心eurka地址


#endpoints:
#  shutdown:
#    enabled: true #开启优雅关闭方式
#management:
#  security:
#    enabled: false